name: main
on:
  workflow_dispatch:
  repository_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      # Chromium is already installed!
      - name: Install software
        run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests webdriver-manager selenium undetected_chromedriver
      - name: Run the py script
        env:
            BASE_URL: ${{ secrets.BASE_URL }}
            UID: ${{ secrets.UID }}
            API_KEY: ${{ secrets.API_KEY }}
            UID2: ${{ secrets.UID2 }}
            API_KEY2: ${{ secrets.API_KEY2 }}
        run: |
            python run.py
